---
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - bundle install
build_script:
  - rake -rdevkit compile
test_script:
  - rake test
  - rake install
deploy: off
environment:
  matrix:
    - ruby_version: "26"
    - ruby_version: "26-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
